# Generated by Django 3.0.3 on 2020-03-20 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0004_auto_20200311_1435'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='name',
            field=models.CharField(max_length=100, null=True, verbose_name='汽车名称'),
        ),
        migrations.AddField(
            model_name='manufacturer',
            name='name',
            field=models.CharField(max_length=100, null=True, verbose_name='制造商名称'),
        ),
    ]
